/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KTechPluginGuard
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/constants.ts
var PLUGIN_NAME = "K-Tech Plugin Guard";
var FUNDING_URL = "https://buymeacoffee.com/k_tech_studio";
var COMMUNITY_PLUGINS_URL = "https://raw.githubusercontent.com/obsidianmd/obsidian-releases/master/community-plugins.json";
var GITHUB_API = "https://api.github.com";
var CHECK_CONCURRENCY = 4;
var USER_AGENT = "k-tech-plugin-guard";

// src/github.ts
var import_obsidian = require("obsidian");
function authHeaders(token) {
  const headers = {
    Accept: "application/vnd.github+json",
    "User-Agent": USER_AGENT
  };
  const trimmed = token.trim();
  if (trimmed) {
    headers.Authorization = `Bearer ${trimmed}`;
  }
  return headers;
}
var RateLimitError = class extends Error {
  constructor() {
    super("GitHub API rate limit exceeded");
    this.name = "RateLimitError";
  }
};
async function fetchJson(url, token = "") {
  const res = await (0, import_obsidian.requestUrl)({
    url,
    method: "GET",
    headers: authHeaders(token),
    throw: false
  });
  const remaining = res.headers["x-ratelimit-remaining"];
  if (res.status === 403 && remaining === "0") {
    throw new RateLimitError();
  }
  let json = null;
  const text = res.text || "";
  if (text) {
    try {
      json = JSON.parse(text);
    } catch (e) {
      json = null;
    }
  }
  return { status: res.status, json, text };
}
async function fetchText(url, token = "") {
  var _a;
  const res = await (0, import_obsidian.requestUrl)({
    url,
    method: "GET",
    headers: authHeaders(token),
    throw: false
  });
  if (res.status === 403) {
    const remaining = res.headers["x-ratelimit-remaining"];
    if (remaining === "0") throw new RateLimitError();
  }
  if (res.status < 200 || res.status >= 300) return null;
  return (_a = res.text) != null ? _a : null;
}
async function fetchLatestRelease(repo, token = "") {
  const { status, json } = await fetchJson(
    `${GITHUB_API}/repos/${repo}/releases/latest`,
    token
  );
  if (status === 404 || !json) return null;
  if (status < 200 || status >= 300) return null;
  const tagName = String(json.tag_name || "").trim();
  if (!tagName) return null;
  const assets = [];
  const rawAssets = Array.isArray(json.assets) ? json.assets : [];
  for (const asset of rawAssets) {
    const name = String(asset.name || "").trim();
    const downloadUrl = String(asset.browser_download_url || "").trim();
    if (name && downloadUrl) {
      assets.push({ name, downloadUrl });
    }
  }
  return {
    tagName,
    name: String(json.name || tagName),
    prerelease: Boolean(json.prerelease),
    publishedAt: String(json.published_at || ""),
    notes: String(json.body || ""),
    assets
  };
}
async function mapPool(items, limit, worker) {
  const out = new Array(items.length);
  let next = 0;
  const runners = Array.from({ length: Math.max(1, limit) }, async () => {
    while (next < items.length) {
      const i = next++;
      out[i] = await worker(items[i], i);
    }
  });
  await Promise.all(runners);
  return out;
}

// src/plugins-api.ts
function getPluginsApi(app) {
  const plugins = app.plugins;
  if (!plugins || !plugins.manifests) {
    throw new Error("Community plugins API is not available");
  }
  return plugins;
}

// src/lazy.ts
function isMobileApp(app) {
  const maybe = app;
  return Boolean(maybe.isMobile);
}
async function readLazySettings(app) {
  const path = `${app.vault.configDir}/plugins/lazy-plugins/data.json`;
  try {
    const exists = await app.vault.adapter.exists(path);
    if (!exists) return null;
    const raw = await app.vault.adapter.read(path);
    const data = JSON.parse(raw);
    if (data.dualConfigs && isMobileApp(app) && data.mobile) {
      return data.mobile;
    }
    return data.desktop || data.mobile || null;
  } catch (e) {
    return null;
  }
}
function lazyStartupFor(pluginId, lazy) {
  var _a, _b;
  if (!lazy) return null;
  const configured = (_b = (_a = lazy.plugins) == null ? void 0 : _a[pluginId]) == null ? void 0 : _b.startupType;
  if (configured) return configured;
  if (lazy.defaultStartupType) return lazy.defaultStartupType;
  return null;
}
function isEffectivelyDisabled(plugin, settings, lazy) {
  if (!settings.ignoreDisabled) return false;
  if (settings.lazyStrategy === "lazy-config" && lazy) {
    const startup = lazyStartupFor(plugin.id, lazy);
    if (startup === "disabled") return true;
    if (startup === "instant" || startup === "short" || startup === "long") {
      return false;
    }
  }
  return !plugin.enabled;
}
function waitMs(ms) {
  return new Promise((resolve) => window.setTimeout(resolve, ms));
}
async function applyLazyWait(app, settings, pendingIds, _lazy) {
  if (settings.lazyStrategy === "none") return;
  if (settings.lazyStrategy === "fixed-delay") {
    await waitMs(Math.max(0, settings.fixedDelaySeconds) * 1e3);
    return;
  }
  if (settings.lazyStrategy !== "wait-loaded") return;
  const timeout = Math.max(1, settings.waitLoadedTimeoutSeconds) * 1e3;
  const started = Date.now();
  while (Date.now() - started < timeout) {
    const api = getPluginsApi(app);
    const remaining = pendingIds.filter((id) => !api.plugins[id]);
    if (!remaining.length) return;
    await waitMs(400);
  }
}
function pendingLazyIds(plugins, lazy, apiPlugins) {
  if (!lazy) return [];
  return plugins.filter((p) => {
    const startup = lazyStartupFor(p.id, lazy);
    if (startup !== "short" && startup !== "long") return false;
    return !apiPlugins[p.id];
  }).map((p) => p.id);
}

// src/registry.ts
async function loadCommunityRegistry() {
  const map = /* @__PURE__ */ new Map();
  const { status, json } = await fetchJson(COMMUNITY_PLUGINS_URL);
  if (status < 200 || status >= 300 || !Array.isArray(json)) {
    throw new Error("Could not load the community plugin directory");
  }
  for (const row of json) {
    if (!row || typeof row !== "object") continue;
    const rec = row;
    const id = String(rec.id || "").trim();
    const repo = String(rec.repo || "").trim();
    if (id && repo && repo.indexOf("/") !== -1) {
      map.set(id, repo);
    }
  }
  return map;
}

// src/i18n.ts
function isJapaneseLocale() {
  try {
    const lang = String(
      window.localStorage && window.localStorage.getItem("language") || ""
    ).toLowerCase();
    if (lang.startsWith("ja")) return true;
  } catch (e) {
  }
  try {
    return String(navigator.language || "").toLowerCase().startsWith("ja");
  } catch (e) {
    return false;
  }
}
function t(ja, en) {
  return isJapaneseLocale() ? ja : en;
}

// src/version.ts
function normalizeVersion(raw) {
  return String(raw || "").trim().replace(/^v/i, "");
}
function splitVersion(raw) {
  const normalized = normalizeVersion(raw);
  const dash = normalized.indexOf("-");
  const core = dash === -1 ? normalized : normalized.slice(0, dash);
  const pre = dash === -1 ? "" : normalized.slice(dash + 1).toLowerCase();
  const parts = core.split(".").map((n) => {
    const v = parseInt(n, 10);
    return Number.isFinite(v) ? v : 0;
  });
  while (parts.length < 3) parts.push(0);
  return { parts: parts.slice(0, 3), pre };
}
function compareVersions(a, b) {
  const left = splitVersion(a);
  const right = splitVersion(b);
  for (let i = 0; i < 3; i++) {
    if (left.parts[i] !== right.parts[i]) return left.parts[i] - right.parts[i];
  }
  if (!left.pre && right.pre) return 1;
  if (left.pre && !right.pre) return -1;
  return left.pre.localeCompare(right.pre);
}
function isNewerVersion(remote, local) {
  return compareVersions(remote, local) > 0;
}
function isBetaVersion(version, releaseName) {
  const text = `${normalizeVersion(version)} ${releaseName || ""}`.toLowerCase();
  return /\b(alpha|beta|rc|pre|preview|canary|nightly)\b/.test(text);
}
function daysSince(iso) {
  const ms = Date.parse(iso);
  if (!Number.isFinite(ms)) return 0;
  return Math.max(0, (Date.now() - ms) / 864e5);
}

// src/check.ts
function listInstalled(app) {
  const api = getPluginsApi(app);
  const configDir = app.vault.configDir;
  const out = [];
  for (const id of Object.keys(api.manifests)) {
    const manifest = api.manifests[id];
    if (!manifest) continue;
    out.push({
      id: manifest.id,
      name: manifest.name || manifest.id,
      version: manifest.version || "0",
      dir: `${configDir}/plugins/${manifest.id}`,
      enabled: api.enabledPlugins.has(manifest.id)
    });
  }
  out.sort((a, b) => a.name.localeCompare(b.name));
  return out;
}
async function checkForUpdates(app, settings) {
  const lazy = await readLazySettings(app);
  let installed = listInstalled(app);
  const api = getPluginsApi(app);
  const pending = pendingLazyIds(installed, lazy, api.plugins);
  await applyLazyWait(app, settings, pending, lazy);
  installed = listInstalled(app);
  const registry = await loadCommunityRegistry();
  const candidates = installed.filter(
    (plugin) => !isEffectivelyDisabled(plugin, settings, lazy)
  );
  const updates = [];
  const errors = [];
  let skipped = installed.length - candidates.length;
  let rateLimited = false;
  await mapPool(candidates, CHECK_CONCURRENCY, async (plugin) => {
    if (rateLimited) return;
    const repo = registry.get(plugin.id);
    if (!repo) {
      skipped += 1;
      return;
    }
    try {
      const release = await fetchLatestRelease(repo, settings.githubToken);
      if (!release) {
        skipped += 1;
        return;
      }
      const latestVersion = normalizeVersion(release.tagName);
      if (!isNewerVersion(latestVersion, plugin.version)) return;
      const beta = release.prerelease || isBetaVersion(latestVersion, release.name);
      if (settings.ignoreBeta && beta) return;
      const daysOld = daysSince(release.publishedAt);
      const tooNew = settings.daysUntilShow > 0 && daysOld < settings.daysUntilShow;
      if (tooNew) return;
      updates.push({
        id: plugin.id,
        name: plugin.name,
        currentVersion: plugin.version,
        latestVersion,
        repo,
        tagName: release.tagName,
        publishedAt: release.publishedAt,
        notes: release.notes || "",
        isBeta: beta,
        daysOld,
        assets: release.assets,
        tooNew: false
      });
    } catch (err) {
      if (err instanceof RateLimitError) {
        rateLimited = true;
        errors.push(
          t(
            "GitHub \u306E\u56DE\u6570\u5236\u9650\u306B\u9054\u3057\u307E\u3057\u305F\u3002\u8A2D\u5B9A\u306E\u30C8\u30FC\u30AF\u30F3\u3092\u4F7F\u3046\u304B\u3001\u6642\u9593\u3092\u304A\u3044\u3066\u518D\u8A66\u884C\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
            "GitHub rate limit reached. Wait, or add a personal token in settings."
          )
        );
        return;
      }
      errors.push(`${plugin.name}: ${err instanceof Error ? err.message : String(err)}`);
    }
  });
  updates.sort((a, b) => a.name.localeCompare(b.name));
  return { updates, skipped, errors, rateLimited };
}

// src/funding.ts
var import_obsidian2 = require("obsidian");
var FundingModal = class extends import_obsidian2.Modal {
  constructor(app, kind, version) {
    super(app);
    this.kind = kind;
    this.version = version;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText(PLUGIN_NAME);
    const heading = this.kind === "install" ? t("\u30A4\u30F3\u30B9\u30C8\u30FC\u30EB\u3042\u308A\u304C\u3068\u3046\u3054\u3056\u3044\u307E\u3059", "Thanks for installing!") : t(`v${this.version} \u306B\u66F4\u65B0\u3057\u307E\u3057\u305F`, `Updated to ${this.version}`);
    contentEl.createEl("h3", { text: heading });
    contentEl.createEl("p", {
      text: this.kind === "install" ? t(
        "\u30B3\u30DF\u30E5\u30CB\u30C6\u30A3\u30D7\u30E9\u30B0\u30A4\u30F3\u306E\u66F4\u65B0\u3092\u3001\u9078\u3093\u3067\u304B\u3089\u5165\u308C\u3089\u308C\u307E\u3059\u3002\u5F79\u306B\u7ACB\u3063\u305F\u3089\u958B\u767A\u306E\u52B1\u307F\u306B\u3057\u3066\u304F\u3060\u3055\u3044\uFF08\u4EFB\u610F\uFF09\u3002",
        "Check community plugin updates, then install only what you select. If this helps, consider supporting development (optional)."
      ) : t(
        "\u65B0\u3057\u3044\u7248\u306B\u66F4\u65B0\u3055\u308C\u307E\u3057\u305F\u3002\u5F79\u306B\u7ACB\u3063\u305F\u3089\u3001\u958B\u767A\u306E\u52B1\u307F\u306B\u3057\u3066\u304F\u3060\u3055\u3044\uFF08\u4EFB\u610F\uFF09\u3002",
        "Thanks for updating. If this plugin helps your workflow, consider supporting development (optional)."
      )
    });
    const actions = contentEl.createDiv({ cls: "modal-button-container" });
    const coffeeBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: t("\u2615 Buy Me a Coffee", "\u2615 Buy Me a Coffee")
    });
    coffeeBtn.addEventListener("click", () => {
      window.open(FUNDING_URL, "_blank");
      this.close();
    });
    const laterBtn = actions.createEl("button", {
      text: t("\u3042\u3068\u3067", "Maybe later")
    });
    laterBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
function openFundingModal(app, kind, version) {
  new FundingModal(app, kind, version).open();
}

// src/modals.ts
var import_obsidian3 = require("obsidian");

// src/installer.ts
function assetUrl(update, fileName) {
  const found = update.assets.find((a) => a.name === fileName);
  if (found) return found.downloadUrl;
  if (fileName === "styles.css") return null;
  return `https://github.com/${update.repo}/releases/download/${update.tagName}/${fileName}`;
}
async function installUpdate(app, update, token) {
  const mainUrl = assetUrl(update, "main.js");
  const manifestUrl = assetUrl(update, "manifest.json");
  if (!mainUrl || !manifestUrl) {
    throw new Error("Release is missing main.js or manifest.json");
  }
  const mainJs = await fetchText(mainUrl, token);
  const manifest = await fetchText(manifestUrl, token);
  if (!mainJs || !manifest) {
    throw new Error("Release is missing main.js or manifest.json");
  }
  let styles = null;
  const stylesUrl = assetUrl(update, "styles.css");
  if (stylesUrl) {
    try {
      styles = await fetchText(stylesUrl, token);
    } catch (err) {
      if (err instanceof RateLimitError) throw err;
      styles = null;
    }
  }
  const api = getPluginsApi(app);
  const wasEnabled = api.enabledPlugins.has(update.id);
  if (wasEnabled) {
    await api.disablePlugin(update.id);
  }
  const dir = `${app.vault.configDir}/plugins/${update.id}`;
  if (!await app.vault.adapter.exists(dir)) {
    await app.vault.adapter.mkdir(dir);
  }
  await app.vault.adapter.write(`${dir}/main.js`, mainJs);
  await app.vault.adapter.write(`${dir}/manifest.json`, manifest);
  if (styles != null && styles.length) {
    await app.vault.adapter.write(`${dir}/styles.css`, styles);
  }
  if (typeof api.loadManifests === "function") {
    await api.loadManifests();
  }
  if (wasEnabled) {
    await api.enablePlugin(update.id);
  }
}

// src/modals.ts
var NoUpdatesModal = class extends import_obsidian3.Modal {
  constructor(app, extra) {
    super(app);
    this.extra = extra;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    titleEl.setText(PLUGIN_NAME);
    contentEl.createEl("h3", {
      text: t("\u4ECA\u306E\u3068\u3053\u308D\u66F4\u65B0\u306F\u3042\u308A\u307E\u305B\u3093", "No updates right now")
    });
    contentEl.createEl("p", {
      text: t(
        "\u5C0E\u5165\u3057\u3066\u3044\u308B\u30B3\u30DF\u30E5\u30CB\u30C6\u30A3\u30D7\u30E9\u30B0\u30A4\u30F3\u306F\u3001\u78BA\u8A8D\u3057\u305F\u7BC4\u56F2\u3067\u306F\u6700\u65B0\u3067\u3059\u3002",
        "Installed community plugins are up to date for this check."
      )
    });
    if (this.extra.length) {
      const list = contentEl.createEl("ul", { cls: "ktech-guard-notes" });
      for (const line of this.extra) {
        list.createEl("li", { text: line });
      }
    }
    const actions = contentEl.createDiv({ cls: "modal-button-container" });
    const closeBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: t("\u9589\u3058\u308B", "Close")
    });
    closeBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
var UpdatesModal = class extends import_obsidian3.Modal {
  constructor(app, updates, token, extra, onDone) {
    super(app);
    this.updates = updates;
    this.token = token;
    this.extra = extra;
    this.onDone = onDone;
    this.selected = /* @__PURE__ */ new Set();
    this.busy = false;
    for (const update of updates) {
      this.selected.add(update.id);
    }
  }
  onOpen() {
    this.render();
  }
  onClose() {
    this.contentEl.empty();
  }
  render() {
    const { contentEl, titleEl } = this;
    contentEl.empty();
    titleEl.setText(PLUGIN_NAME);
    contentEl.createEl("h3", {
      text: t(
        `${this.updates.length} \u4EF6\u306E\u66F4\u65B0\u304C\u3042\u308A\u307E\u3059`,
        `${this.updates.length} update(s) available`
      )
    });
    contentEl.createEl("p", {
      text: t(
        "\u5165\u308C\u308B\u30D7\u30E9\u30B0\u30A4\u30F3\u306B\u30C1\u30A7\u30C3\u30AF\u3092\u4ED8\u3051\u3066\u304B\u3089\u66F4\u65B0\u3057\u3066\u304F\u3060\u3055\u3044\u3002GitHub Release \u306E\u914D\u5E03\u30D5\u30A1\u30A4\u30EB\u3092\u4F7F\u3044\u307E\u3059\u3002",
        "Select the plugins to install. Files come from each GitHub Release (same as the official updater)."
      )
    });
    if (this.extra.length) {
      const notes = contentEl.createEl("ul", { cls: "ktech-guard-notes" });
      for (const line of this.extra) {
        notes.createEl("li", { text: line });
      }
    }
    new import_obsidian3.Setting(contentEl).setName(t("\u3059\u3079\u3066\u9078\u629E", "Select all")).addToggle((toggle) => {
      toggle.setValue(this.selected.size === this.updates.length);
      toggle.onChange((on) => {
        this.selected.clear();
        if (on) {
          for (const update of this.updates) this.selected.add(update.id);
        }
        this.render();
      });
    });
    for (const update of this.updates) {
      const row = new import_obsidian3.Setting(contentEl);
      row.setName(update.name);
      const beta = update.isBeta ? t("\uFF08\u30D9\u30FC\u30BF\uFF09", " (beta)") : "";
      row.setDesc(
        `${update.currentVersion} \u2192 ${update.latestVersion}${beta}` + (update.notes ? `
${update.notes.trim().slice(0, 280)}${update.notes.length > 280 ? "\u2026" : ""}` : "")
      );
      row.addToggle((toggle) => {
        toggle.setValue(this.selected.has(update.id));
        toggle.onChange((on) => {
          if (on) this.selected.add(update.id);
          else this.selected.delete(update.id);
        });
      });
    }
    const actions = contentEl.createDiv({ cls: "modal-button-container" });
    const updateBtn = actions.createEl("button", {
      cls: "mod-cta",
      text: t("\u9078\u629E\u3057\u305F\u30D7\u30E9\u30B0\u30A4\u30F3\u3092\u66F4\u65B0", "Update selected")
    });
    updateBtn.disabled = this.busy;
    updateBtn.addEventListener("click", () => {
      void this.applySelected();
    });
    const cancelBtn = actions.createEl("button", {
      text: t("\u30AD\u30E3\u30F3\u30BB\u30EB", "Cancel")
    });
    cancelBtn.addEventListener("click", () => this.close());
  }
  async applySelected() {
    if (this.busy) return;
    const chosen = this.updates.filter((u) => this.selected.has(u.id));
    if (!chosen.length) {
      new import_obsidian3.Notice(t("\u30D7\u30E9\u30B0\u30A4\u30F3\u304C\u9078\u629E\u3055\u308C\u3066\u3044\u307E\u305B\u3093", "No plugins selected"));
      return;
    }
    this.busy = true;
    this.render();
    let ok = 0;
    const failed = [];
    for (const update of chosen) {
      try {
        new import_obsidian3.Notice(
          t(`${update.name} \u3092\u66F4\u65B0\u3057\u3066\u3044\u307E\u3059\u2026`, `Updating ${update.name}\u2026`)
        );
        await installUpdate(this.app, update, this.token);
        ok += 1;
      } catch (err) {
        if (err instanceof RateLimitError) {
          failed.push(t("GitHub \u306E\u56DE\u6570\u5236\u9650\u306B\u9054\u3057\u307E\u3057\u305F", "GitHub rate limit reached"));
          break;
        }
        failed.push(
          `${update.name}: ${err instanceof Error ? err.message : String(err)}`
        );
      }
    }
    this.busy = false;
    this.close();
    if (ok) {
      new import_obsidian3.Notice(
        t(`${ok} \u4EF6\u3092\u66F4\u65B0\u3057\u307E\u3057\u305F`, `Updated ${ok} plugin(s)`)
      );
    }
    if (failed.length) {
      new import_obsidian3.Notice(failed.join("\n"), 8e3);
    }
    this.onDone();
  }
};

// src/settings.ts
var import_obsidian4 = require("obsidian");
var GuardSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", {
      text: t("K-Tech Plugin Guard", "K-Tech Plugin Guard")
    });
    new import_obsidian4.Setting(containerEl).setName(t("\u8D77\u52D5\u6642\u306B\u78BA\u8A8D\u3059\u308B", "Check on startup")).setDesc(
      t(
        "\u30AA\u30D5\u306E\u3068\u304D\u306F\u3001\u30DC\u30BF\u30F3\u307E\u305F\u306F\u30B3\u30DE\u30F3\u30C9\u3067\u306E\u307F GitHub \u3092\u898B\u306B\u884C\u304D\u307E\u3059\u3002",
        "When off, GitHub is contacted only from the button or command."
      )
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.checkOnStartup);
      toggle.onChange(async (value) => {
        this.plugin.settings.checkOnStartup = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName(t("\u7121\u52B9\u30D7\u30E9\u30B0\u30A4\u30F3\u306F\u5BFE\u8C61\u5916", "Ignore disabled plugins")).setDesc(
      t(
        "Lazy Loader \u304C\u3042\u308B\u3068\u304D\u306F\u3001\u305D\u3061\u3089\u306E\u300C\u7121\u52B9\u300D\u3060\u3051\u3092\u7121\u52B9\u3068\u307F\u306A\u3057\u307E\u3059\uFF08\u9045\u5EF6\u8AAD\u307F\u8FBC\u307F\u306F\u5BFE\u8C61\u306B\u6B8B\u3057\u307E\u3059\uFF09\u3002",
        "With Lazy Loader, only plugins it marks Disabled are skipped. Delayed plugins stay included."
      )
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.ignoreDisabled);
      toggle.onChange(async (value) => {
        this.plugin.settings.ignoreDisabled = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName(t("\u30D9\u30FC\u30BF\u7248\u3092\u51FA\u3055\u306A\u3044", "Hide beta versions")).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.ignoreBeta);
      toggle.onChange(async (value) => {
        this.plugin.settings.ignoreBeta = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName(t("\u516C\u958B\u304B\u3089\u4F55\u65E5\u5F85\u3064\u304B", "Days to wait after a release")).setDesc(
      t(
        "0 \u306A\u3089\u3001\u78BA\u8A8D\u3057\u305F\u6642\u70B9\u306E\u6700\u65B0\u3092\u51FA\u3057\u307E\u3059\u3002",
        "0 shows a release as soon as this check finds it."
      )
    ).addSlider((slider) => {
      slider.setLimits(0, 14, 1);
      slider.setDynamicTooltip();
      slider.setValue(this.plugin.settings.daysUntilShow);
      slider.onChange(async (value) => {
        this.plugin.settings.daysUntilShow = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName(t("\u9045\u5EF6\u8AAD\u307F\u8FBC\u307F\u306E\u6271\u3044", "Delayed plugin handling")).setDesc(
      t(
        "Lazy Loader \u5229\u7528\u6642\u306B\u3001\u307E\u3060\u8AAD\u307F\u8FBC\u307E\u308C\u3066\u3044\u306A\u3044\u30D7\u30E9\u30B0\u30A4\u30F3\u3092\u7121\u52B9\u3068\u8AA4\u3089\u306A\u3044\u305F\u3081\u306E\u65B9\u6CD5\u3067\u3059\u3002",
        "Avoid treating Lazy Loader delayed plugins as disabled."
      )
    ).addDropdown((dropdown) => {
      dropdown.addOption(
        "lazy-config",
        t("Lazy Loader \u306E\u8A2D\u5B9A\u3092\u8AAD\u3080\uFF08\u63A8\u5968\uFF09", "Read Lazy Loader settings (recommended)")
      );
      dropdown.addOption(
        "wait-loaded",
        t("\u8AAD\u307F\u8FBC\u307F\u5B8C\u4E86\u307E\u3067\u5F85\u3064", "Wait until delayed plugins load")
      );
      dropdown.addOption(
        "fixed-delay",
        t("\u56FA\u5B9A\u79D2\u6570\u5F85\u3064", "Wait a fixed number of seconds")
      );
      dropdown.addOption("none", t("\u5F85\u305F\u306A\u3044", "Do not wait"));
      dropdown.setValue(this.plugin.settings.lazyStrategy);
      dropdown.onChange(async (value) => {
        this.plugin.settings.lazyStrategy = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.lazyStrategy === "fixed-delay") {
      new import_obsidian4.Setting(containerEl).setName(t("\u5F85\u6A5F\u79D2\u6570", "Wait seconds")).addSlider((slider) => {
        slider.setLimits(1, 30, 1);
        slider.setDynamicTooltip();
        slider.setValue(this.plugin.settings.fixedDelaySeconds);
        slider.onChange(async (value) => {
          this.plugin.settings.fixedDelaySeconds = value;
          await this.plugin.saveSettings();
        });
      });
    }
    if (this.plugin.settings.lazyStrategy === "wait-loaded") {
      new import_obsidian4.Setting(containerEl).setName(t("\u5F85\u3061\u6642\u9593\u306E\u4E0A\u9650\uFF08\u79D2\uFF09", "Wait timeout (seconds)")).addSlider((slider) => {
        slider.setLimits(5, 60, 1);
        slider.setDynamicTooltip();
        slider.setValue(this.plugin.settings.waitLoadedTimeoutSeconds);
        slider.onChange(async (value) => {
          this.plugin.settings.waitLoadedTimeoutSeconds = value;
          await this.plugin.saveSettings();
        });
      });
    }
    new import_obsidian4.Setting(containerEl).setName(t("GitHub \u30C8\u30FC\u30AF\u30F3\uFF08\u4EFB\u610F\uFF09", "GitHub token (optional)")).setDesc(
      t(
        "\u672A\u8A8D\u8A3C\u306F1\u6642\u9593\u3042\u305F\u308A\u7D0460\u56DE\u3067\u3059\u3002\u591A\u3044\u3068\u304D\u306F Fine-grained \u307E\u305F\u306F classic \u306E PAT \u3092\u30ED\u30FC\u30AB\u30EB\u306B\u3060\u3051\u4FDD\u5B58\u3057\u307E\u3059\u3002\u4F5C\u8005\u30B5\u30FC\u30D0\u30FC\u306B\u306F\u9001\u308A\u307E\u305B\u3093\u3002",
        "Unauthenticated checks are about 60 GitHub requests per hour. A PAT is stored locally only and is never sent to a K-Tech server."
      )
    ).addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder("ghp_\u2026");
      text.setValue(this.plugin.settings.githubToken);
      text.onChange(async (value) => {
        this.plugin.settings.githubToken = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Buy Me a Coffee").setDesc(
      t(
        "\u958B\u767A\u652F\u63F4\u306F\u4EFB\u610F\u3067\u3059\u3002",
        "Support is optional."
      )
    ).addButton((button) => {
      button.setButtonText("Buy Me a Coffee");
      button.setCta();
      button.onClick(() => {
        window.open(FUNDING_URL, "_blank");
      });
    });
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  githubToken: "",
  ignoreDisabled: true,
  ignoreBeta: true,
  daysUntilShow: 0,
  lazyStrategy: "lazy-config",
  fixedDelaySeconds: 8,
  waitLoadedTimeoutSeconds: 25,
  checkOnStartup: false
};
function parseStorage(raw) {
  if (!raw || typeof raw !== "object") {
    return { settings: { ...DEFAULT_SETTINGS } };
  }
  const data = raw;
  if ("settings" in data && data.settings && typeof data.settings === "object") {
    return {
      settings: Object.assign({}, DEFAULT_SETTINGS, data.settings),
      lastSeenVersion: typeof data.lastSeenVersion === "string" ? data.lastSeenVersion : void 0
    };
  }
  return {
    settings: Object.assign({}, DEFAULT_SETTINGS, data),
    lastSeenVersion: void 0
  };
}
function toStorage(settings, lastSeenVersion) {
  return { settings, lastSeenVersion };
}

// src/main.ts
var KTechPluginGuard = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.checking = false;
    this.statusEl = null;
  }
  async onload() {
    await this.loadSettings();
    this.statusEl = this.addStatusBarItem();
    this.statusEl.addClass("ktech-guard-status");
    this.setStatus(t("\u78BA\u8A8D", "Check"));
    this.statusEl.addEventListener("click", () => {
      void this.runCheck();
    });
    this.addRibbonIcon("shield-check", PLUGIN_NAME, () => {
      void this.runCheck();
    });
    this.addCommand({
      id: "check-plugin-updates",
      name: t("\u30D7\u30E9\u30B0\u30A4\u30F3\u306E\u66F4\u65B0\u3092\u78BA\u8A8D", "Check for plugin updates"),
      callback: () => {
        void this.runCheck();
      }
    });
    this.addSettingTab(new GuardSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      void this.maybeShowFundingModal();
      if (this.settings.checkOnStartup) {
        void this.runCheck();
      }
    });
  }
  onunload() {
    this.statusEl = null;
  }
  async loadSettings() {
    const storage = parseStorage(await this.loadData());
    this.settings = storage.settings;
    this.lastSeenVersion = storage.lastSeenVersion;
  }
  async saveSettings() {
    await this.saveData(toStorage(this.settings, this.lastSeenVersion));
  }
  setStatus(text) {
    if (!this.statusEl) return;
    this.statusEl.setText(`Guard ${text}`);
    this.statusEl.setAttribute("aria-label", `${PLUGIN_NAME}: ${text}`);
  }
  async maybeShowFundingModal() {
    const currentVersion = this.manifest.version;
    if (this.lastSeenVersion === currentVersion) return;
    const kind = this.lastSeenVersion ? "update" : "install";
    window.setTimeout(() => {
      openFundingModal(this.app, kind, currentVersion);
    }, 800);
    this.lastSeenVersion = currentVersion;
    await this.saveSettings();
  }
  async runCheck() {
    if (this.checking) {
      new import_obsidian5.Notice(t("\u3059\u3067\u306B\u78BA\u8A8D\u4E2D\u3067\u3059", "Already checking"));
      return;
    }
    this.checking = true;
    this.setStatus(t("\u78BA\u8A8D\u4E2D\u2026", "Checking\u2026"));
    new import_obsidian5.Notice(t("\u30D7\u30E9\u30B0\u30A4\u30F3\u306E\u66F4\u65B0\u3092\u78BA\u8A8D\u3057\u3066\u3044\u307E\u3059\u2026", "Checking plugin updates\u2026"));
    try {
      const result = await checkForUpdates(this.app, this.settings);
      const extra = [];
      if (result.rateLimited) {
        extra.push(
          t(
            "GitHub \u306E\u56DE\u6570\u5236\u9650\u306B\u9054\u3057\u307E\u3057\u305F\u3002\u8A2D\u5B9A\u306E\u30C8\u30FC\u30AF\u30F3\u3092\u4F7F\u3046\u304B\u3001\u6642\u9593\u3092\u304A\u3044\u3066\u518D\u8A66\u884C\u3057\u3066\u304F\u3060\u3055\u3044\u3002",
            "GitHub rate limit reached. Add a token in settings, or try again later."
          )
        );
      }
      for (const err of result.errors) extra.push(err);
      if (!result.updates.length) {
        this.setStatus(t("\u6700\u65B0", "Up to date"));
        new NoUpdatesModal(this.app, extra).open();
        return;
      }
      this.setStatus(String(result.updates.length));
      new UpdatesModal(
        this.app,
        result.updates,
        this.settings.githubToken,
        extra,
        () => {
          this.setStatus(t("\u78BA\u8A8D", "Check"));
        }
      ).open();
    } catch (err) {
      this.setStatus(t("\u30A8\u30E9\u30FC", "Error"));
      new import_obsidian5.Notice(
        t(
          `\u78BA\u8A8D\u306B\u5931\u6557\u3057\u307E\u3057\u305F: ${err instanceof Error ? err.message : String(err)}`,
          `Check failed: ${err instanceof Error ? err.message : String(err)}`
        ),
        8e3
      );
    } finally {
      this.checking = false;
    }
  }
};
